#!/bin/bash
# YAIS: yet another installation script
#
set -e
VERSION="1.0 Alpha"
if [ ${UID} -ne 0 ]; then
	echo "You must be root, but Arch is the best!"
	exit
fi

for FILE in yais.d/*.sh
do
	. $FILE
done
PROFILEDIR=yais.d/profile/
cp "${PROFILEDIR}/archlinux.sh" /tmp/yais.profile
PROFILE=/tmp/yais.profile
EDITOR=vi
funcs=(yais_config editor partition mount_disk mirrorselect testnet pkgstrap install_grub fstab setpass yais_chroot exit)
menuname=(
	"Config YAIS" \
	"Select an editor" \
	"Partitioning" \
	"Mount your partitions" \
	"Select a mirror" \
	"Test the internet" \
	"Install packages" \
	"Install grub" \
	"Generate fstab" \
	"Set root password" \
	"Chroot"
	"Exit YAIS" \
	)
TODO=1

menu(){
	local MENU
	local DEFOPT="--default-item ${TODO}"
	local _i
	MENU="dialog --stdout ${DEFOPT} --menu \"YAIS ${VERSION}\" 0 0 0"
	for _i in $(seq -s ' ' 0 $((${#menuname[@]}-1))) 
	do
		MENU="${MENU} ${_i} \"${menuname[${_i}]}\""
	done
	eval ${MENU}
}

while true
do
	FUNCID=$(menu)
	${funcs[$FUNCID]}
	if [ $FUNCID -gt 0 ]; then
		let TODO=FUNCID+1
	fi
done

